// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMClyJFm5ReotW8kWYLgh0N3gaI95Fxtk',
    appId: '1:801160719265:android:3ea87e5efa33a75b82b9e0',
    messagingSenderId: '801160719265',
    projectId: 'sundial-827d8',
    storageBucket: 'sundial-827d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS67XbgwLUhSWySnDS9iYqciIqe__CEeY',
    appId: '1:801160719265:ios:56f93fe6df9b34b582b9e0',
    messagingSenderId: '801160719265',
    projectId: 'sundial-827d8',
    storageBucket: 'sundial-827d8.firebasestorage.app',
    androidClientId: '801160719265-dk3outjjnsv520dl40ee8q2ri47pcm22.apps.googleusercontent.com',
    iosClientId: '801160719265-ou0rirmev5nk3j5emdvr846t4qsejp0j.apps.googleusercontent.com',
    iosBundleId: 'com.sanoj.sundial',
  );

}